# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class messageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.message = channel.unary_unary(
                '/messageService/message',
                request_serializer=messages__pb2.instructionRequest.SerializeToString,
                response_deserializer=messages__pb2.messageResponse.FromString,
                )
        self.sync = channel.unary_unary(
                '/messageService/sync',
                request_serializer=messages__pb2.instructionRequest.SerializeToString,
                response_deserializer=messages__pb2.messageResponse.FromString,
                )


class messageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_messageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'message': grpc.unary_unary_rpc_method_handler(
                    servicer.message,
                    request_deserializer=messages__pb2.instructionRequest.FromString,
                    response_serializer=messages__pb2.messageResponse.SerializeToString,
            ),
            'sync': grpc.unary_unary_rpc_method_handler(
                    servicer.sync,
                    request_deserializer=messages__pb2.instructionRequest.FromString,
                    response_serializer=messages__pb2.messageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class messageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/messageService/message',
            messages__pb2.instructionRequest.SerializeToString,
            messages__pb2.messageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/messageService/sync',
            messages__pb2.instructionRequest.SerializeToString,
            messages__pb2.messageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
